development:
  adapter: postgresql
  database: fitness-for-students_dev
  host: localhost
  min_messages: warning
  username:

test:
  adapter: postgresql
  database: fitness-for-students_test
  host: localhost
  min_messages: warning
  username: